[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "gemini-api>=0.1.6",
    "google-genai>=1.62.0",
    "nltk==3.9.1",
    "sentence-transformers>=5.1.2",
]
